documents = [
"COVID-19 vaccines are safe and effective according to WHO.",
"Drinking hot water does not cure COVID-19.",
"5G mobile networks do not spread coronavirus.",
"Garlic does not cure COVID-19.",
"Vaccines go through rigorous testing before approval.",
"There is no scientific evidence that home remedies can cure COVID-19 instantly.",
"UNESCO does not award titles such as Best Prime Minister to individuals as its primary role is cultural heritage and education.",
"The United Nations does not declare National Anthems as the best in the world as such claims are common internet hoaxes.",
"NASA does not predict specific dates for world endings or days of darkness due to solar flares.",
"Coconut water contains natural sugars like glucose and fructose and can raise blood sugar levels in people with diabetes.",
"Consuming turmeric has anti-inflammatory properties but there is no clinical evidence that it can cure cancer.",
"Lemon water does not change the pH of the human body to prevent disease because the body strictly regulates its own blood pH.",
"Antibiotics are designed to kill bacteria and are completely ineffective against viral infections like the common cold or flu.",
"The Great Wall of China is not easily visible from the Moon with the naked eye.",
"Storing a smartphone in a bowl of rice is not an effective way to remove internal moisture and can introduce dust into the device.",
"Garlic has antimicrobial properties but cannot cure COVID-19 or viral pneumonia.",
"Drinking hot water does not kill the influenza virus or the coronavirus.",
"Drinking silver water or colloidal silver is not safe and can cause permanent blue-gray skin discoloration called argyria.",
"Human blood is never blue and is always red although the shade varies based on oxygen levels.",
"Bulls are colorblind to red and react to the movement of the matador's cape rather than its color.",
"Cold weather itself does not cause the common cold because viruses are the actual cause.",
"Goldfish do not have a three-second memory and can actually remember information for several months.",
"Houseflies have an average lifespan of 15 to 30 days rather than just 24 hours.",
"Humans use nearly 100 percent of their brains throughout the day rather than just 10 percent.",
"Cracking your knuckles does not cause arthritis or permanent joint damage.",
"Shaving hair does not make it grow back thicker or darker.",
"Eating carrots improves vitamin A levels but will not give you night vision or correct poor eyesight.",
"The five-second rule for dropped food is a myth because bacteria can contaminate food instantly upon contact.",
"Bats are not blind and most species have vision as good as or better than humans.",
"Ostriches do not bury their heads in the sand when scared and instead lie low to appear like a mound.",
"Toads do not give humans warts as warts are caused by human papillomaviruses.",
"Sharks can get cancer and the belief that they are immune is a myth used to sell shark cartilage.",
"Hair and fingernails do not continue to grow after a person dies as the skin simply dries and shrinks.",
"Seasons are caused by the Earth's axial tilt rather than its distance from the Sun.",
"Lightning can and often does strike the same place twice.",
"Glass is a solid at room temperature and not a slow-moving liquid.",
"Using bleach or disinfectant injections to treat a viral infection is extremely dangerous and potentially fatal.",
"5G cellular technology does not cause COVID-19 or weaken the human immune system.",
"Vaccines do not contain microchips or tracking devices for individuals.",
"The Momo Challenge was a viral hoax and not a real threat to children's safety.",
"Bananas do not grow on trees and instead grow on giant herbaceous plants.",
"Tomatoes are botanically fruits even though they are treated as vegetables in culinary contexts.",
"Peanuts are legumes rather than true botanical nuts.",
"An apple a day does not replace the need for professional medical advice or treatment.",
"Poinsettia plants are not deadly to pets or humans although they can cause mild irritation.",
"Salty water does not boil significantly faster than plain water.",
"One human year is not equal to seven dog years as the ratio changes as dogs age.",
"Bulls do not have a specific hatred for the color red.",
"Napoleon Bonaparte was not exceptionally short and was of average height for his time period.",
"Viking helmets did not have horns in historical reality.",
"Chameleons change color mainly to regulate temperature or communicate rather than just for camouflage.",
"Swallowed chewing gum does not take seven years to digest and passes through the system like other fiber.",
"You do not need to wait 30 minutes after eating before it is safe to swim.",
"Alcohol does not keep you warm and actually makes you lose core body heat faster by dilating blood vessels.",
"Mother birds will not abandon their babies if a human touches them.",
"Evolution is a scientific theory supported by vast evidence rather than a mere guess.",
"Pure water does not conduct electricity as impurities like minerals and salt are what carry the current.",
"The Sun is white rather than yellow and only appears yellow due to the Earth's atmosphere.",
"Sound cannot travel through the vacuum of space.",
"Mount Everest has the highest altitude but Mauna Kea is the tallest mountain from base to peak.",
"Diamonds are made from highly compressed carbon but are not usually formed from coal.",
"Your heart does not stop when you sneeze.",
"Exercise alone is rarely enough for significant weight loss without corresponding dietary changes.",
"Sweat does not detox the body because that is the primary job of the liver and kidneys.",
"Cell phones do not cause gas station explosions.",
"Using a microwave does not make food radioactive.",
"Reading in the dark may cause eye strain but does not permanently damage your vision.",
"Monosodium Glutamate or MSG has not been scientifically proven to cause Chinese Restaurant Syndrome.",
"Sugar does not cause hyperactivity in children and the behavior is often linked to the excitement of an event.",
"Organic food is not necessarily more nutritious than conventionally grown food.",
"Drinking 8 glasses of water a day is a general guideline rather than a strict medical requirement.",
"Detox teas and juices have no scientific backing for removing toxins from the body.",
"Essential oils can provide pleasant scents but cannot cure serious diseases like polio or cancer.",
"Sitting too close to the television does not cause permanent eye damage.",
"Superfoods is a marketing term rather than a scientific classification.",
"Drinking fruit juice is not as healthy as eating whole fruit due to the loss of fiber.",
"Honey is a form of sugar and can still cause tooth decay and blood sugar spikes.",
"High-fructose corn syrup is nutritionally similar to table sugar.",
"Salt is necessary for body function but excessive intake leads to high blood pressure.",
"Gluten-free diets are only medically necessary for people with celiac disease or gluten sensitivity.",
"Eggs do not significantly raise blood cholesterol for most healthy people.",
"Coffee does not stunt a child's growth.",
"Saturated fats are not the sole cause of heart disease although balance is key.",
"Dark chocolate is healthier than milk chocolate but is still high in calories.",
"Frozen vegetables are often as nutritious as fresh ones because they are frozen at peak ripeness.",
"Microwaving plastic containers can release chemicals into food unless they are labeled microwave safe.",
"Drinking milk does not cause the body to produce more mucus.",
"You cannot sweat out a fever by wearing heavy blankets.",
"Feeding a cold and starving a fever is a myth because both conditions require proper nutrition and hydration.",
"Probiotics can help gut health but are not a cure-all for all digestive issues.",
"Body Mass Index or BMI is a tool but does not measure body fat percentage or overall health accurately.",
"Walking 10,000 steps was originally a marketing slogan rather than a medical requirement.",
"Stretching before exercise does not necessarily prevent injury and dynamic warm-ups are often better.",
"Muscle does not turn into fat when you stop exercising because they are two different types of tissue.",
"You cannot spot reduce fat from one specific area of the body through exercise alone.",
"Brown sugar is just white sugar with molasses and is not significantly healthier.",
"Sea salt and table salt have roughly the same amount of sodium by weight.",
"Fasting does not reset the immune system in a single day.",
"Alkaline water does not significantly change the body's internal pH levels.",
"Activated charcoal in food can interfere with the absorption of essential medications.",
"Hand sanitizer is not a replacement for washing hands with soap and water for removing certain germs.",
"Flu shots cannot give you the flu because they contain dead or weakened viruses.",
"Natural immunity and vaccine-induced immunity both play critical roles in public health.",
"Herd immunity is reached when a large portion of a population becomes immune to a disease.",
"Homeopathy is not the same as herbal medicine because it uses substances diluted until no original molecules remain.",
"Acupressure can help with pain management but cannot replace surgery for physical injuries.",
"The Earth is an oblate spheroid rather than a flat disk.",
"Gravity exists on the International Space Station and astronauts appear weightless because they are in constant freefall.",
"There is no dark side of the Moon only a far side that receives sunlight.",
"Astrology is a pseudoscience and has no predictive power over human affairs.",
"Mercury being in retrograde is an optical illusion and does not affect human technology or mood.",
"Full moons do not cause an increase in psychiatric admissions or criminal activity.",
"Black holes are not cosmic vacuums and are actually objects with immense gravitational pull.",
"The Bermuda Triangle does not have more disappearances than any other high-traffic ocean area.",
"Psychics have never been scientifically proven to predict the future under controlled conditions.",
"Water does not drain in the opposite direction in the Southern Hemisphere due to the Coriolis effect in small sinks.",
"Humans did land on the Moon in 1969 and the Moon landing hoax has been thoroughly debunked.",
"Ancient aliens did not build the pyramids as they were built by skilled human laborers.",
"Crop circles are man-made landscape art rather than signs of extraterrestrial activity.",
"Area 51 is a real military base but there is no evidence it houses alien technology.",
"The Loch Ness Monster has never been found despite extensive sonar searches.",
"Bigfoot or Sasquatch has no biological evidence such as bones or DNA to support its existence.",
"Ouija boards move due to the ideomotor effect where people move the piece unconsciously.",
"Hypnosis is a state of focused attention rather than a way to brainwash someone.",
"Memory is not like a video recording and is reconstructive and easily influenced.",
"Polygraph tests are not 100 percent accurate and are often inadmissible in court.",
"The Stanford Prison Experiment had significant flaws and does not represent universal human nature.",
"Different areas of the tongue do not map to specific tastes as all tastes can be sensed everywhere.",
"The Alpha Male theory in wolves was based on captive wolves and does not apply to wild wolf families.",
"Lemmings do not commit mass suicide by jumping off cliffs in the wild.",
"Piranhas are generally scavengers and rarely attack humans unless food is extremely scarce.",
"Snakes are not slimy as their skin is dry and made of scales.",
"Most spiders are venomous but very few species are dangerous to humans.",
"Daddy longlegs are not the most poisonous spiders in the world.",
"Bees do not always die after stinging as only honeybees die because of their barbed stingers.",
"Dogs do not see only in black and white and can perceive blues and yellows.",
"Cats always landing on their feet is a tendency but they can still be injured in falls.",
"Owning a cat does not automatically give you Toxoplasmosis if you practice basic hygiene.",
"Humans share about 60 percent of their DNA with bananas.",
"Humans share about 98 percent of their DNA with chimpanzees.",
"DNA is the blueprint of life but epigenetics shows that environment also affects gene expression.",
"Your fingerprints are unique and even identical twins have different fingerprints.",
"The tongue is not the strongest muscle in the body as the masseter jaw muscle is the strongest by weight.",
"Skin is the largest organ of the human body.",
"Most of the dust in your home is mostly dirt, pollen, and fibers rather than dead skin.",
"You lose heat from your whole body rather than just 40 percent through your head.",
"Urine is not sterile even inside the bladder.",
"Drinking your own urine has no proven health benefits and can be harmful.",
"Using a urine soak for jellyfish stings is a myth and can actually make the sting worse.",
"Lightning never strikes the same place twice is a false statement.",
"Positive thinking can improve mood but cannot cure stage IV cancer on its own.",
"Essential oils should not be ingested unless under strict medical supervision.",
"Teething does not cause high fevers in infants.",
"Vaccinating your child does not cause autism as the original study was retracted and found to be fraudulent.",
"Fluorescent lights do not cause skin cancer.",
"Grounding or walking barefoot on grass has psychological benefits but does not align electrical ions for health.",
"Wi-Fi signals are non-ionizing radiation and do not damage human DNA.",
"Microwaves do not destroy the nutrients in food more than boiling or frying does.",
"Using a laptop on your lap will not make you sterile although heat management is important.",
"Artificial sweeteners like aspartame are safe for consumption within regulated limits.",
"Drinking diet soda is not a guaranteed way to lose weight.",
"Carbohydrates are not evil and serve as the body's primary energy source.",
"Low-fat products often contain added sugar to compensate for lost flavor.",
"Breakfast is not necessarily the most important meal of the day for everyone.",
"Red meat consumption is linked to health risks but moderate amounts can be part of a balanced diet.",
"Processed meats are classified as Group 1 carcinogens by the World Health Organization.",
"Eating late at night does not inherently cause more weight gain than eating the same calories during the day.",
"Metabolism can slow down with age but staying active can mitigate the effect.",
"Drinking water before a meal can help with appetite control.",
"Whole grains are better than refined grains because they retain the bran and germ.",
"Raw honey should never be given to infants under one year old due to the risk of botulism.",
"Natural does not always mean safe as substances like arsenic and lead are natural.",
"Sunlight is the best source of Vitamin D but sunscreen is necessary to prevent skin cancer.",
"High-SPF sunscreen does not provide 100 percent protection and must be reapplied frequently.",
"Tanning beds are more dangerous than natural sunlight for skin cancer risk.",
"A base tan does not protect you from a future sunburn.",
"You can still get a sunburn on a cloudy day.",
"Most of the Earth's oxygen comes from phytoplankton in the ocean rather than just trees.",
"Rainwater is generally slightly acidic due to dissolved carbon dioxide from the air.",
"Trees communicate through an underground network of fungi called the Wood Wide Web.",
"Bees are essential for pollinating about one-third of the food humans eat.",
"Using paper bags is not always greener than plastic as it depends on the reuse and recycling process.",
"Electric cars produce fewer emissions over their lifetime than gas cars even considering battery production.",
"Recycling plastic is difficult and only a small percentage of all plastic made has been recycled.",
"Climate change and weather are not the same thing.",
"Nuclear energy is one of the safest forms of energy production per terawatt-hour.",
"Wind turbines do not cause Infrasound Syndrome or significant health issues in humans.",
"Solar panels work on cloudy days although they are less efficient than in direct sun.",
"Desalination is a way to get fresh water from the ocean but is currently energy-intensive.",
"Space junk is a growing problem that threatens satellite communications.",
"The Internet and the World Wide Web are not the same thing.",
"Incognito mode does not make you invisible to your internet service provider or employer.",
"Mac computers can get viruses and malware just like other operating systems.",
"Charging your phone overnight does not overcharge modern lithium-ion batteries.",
"Closing background apps on a smartphone does not actually save battery life.",
"More bars on a phone does not always mean faster internet and just indicates a stronger signal to the tower.",
"Clearing your browser cookies can occasionally fix website loading issues.",
"Two-factor authentication is one of the best ways to secure online accounts.",
"Public Wi-Fi is generally less secure than a private home network.",
"VPNs hide your IP address but do not make you completely untrackable by sophisticated entities.",
"Artificial Intelligence does not think like a human and processes patterns in data.",
"Deepfakes are AI-generated videos that can make people appear to say or do things they did not.",
"Blockchains are a type of distributed ledger technology used for various applications beyond Bitcoin.",
"NFTs are digital certificates of ownership rather than the digital image itself.",
"Quantum computers are not just faster versions of regular computers and solve specific problems using quantum mechanics."
]